name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  push:
    paths:
      - 'papers/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      # main.tex を “確実に” 見つける
      - name: Locate main.tex
        id: locate
        run: |
          echo "PWD=$(pwd)"
          echo "---- repo top ----"; ls -al || true
          echo "---- papers ----";   ls -al papers || true
          TEX=$(git ls-files -- 'papers/**/main.tex' | grep '2025_fefet_cmos018_reliability' || true)
          if [ -z "$TEX" ]; then
            TEX=$(find papers -maxdepth 4 -type f -name main.tex -print | grep '2025_fefet_cmos018_reliability' || true)
          fi
          if [ -z "$TEX" ]; then
            echo "main.tex not found. Tree:"; find . -maxdepth 3 -type d -print
            exit 1
          fi
          echo "TEX=$TEX"           | tee -a $GITHUB_ENV
          echo "TEX_DIR=$(dirname "$TEX")" | tee -a $GITHUB_ENV
          echo "Found: $TEX"

      - name: Build LaTeX (lualatex)
        uses: xu-cheng/latex-action@v3
        with:
          # ここにフルパスを渡す（working_directoryは使わない）
          root_file: ${{ env.TEX }}
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode

      - name: Upload PDF and log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            ${{ env.TEX_DIR }}/main.pdf
            ${{ env.TEX_DIR }}/main.log
          if-no-files-found: warn
