name: Build LCD Driver TiSi2 Paper (IEEE, JP)

on:
  push:
    paths:
      - 'papers/2025_driver_tisi2_ieee/**'
      - '.github/workflows/latex_driver_tisi2_ieee.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX (LuaLaTeX + JP)
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: papers/2025_driver_tisi2_ieee
          root_file: main.tex
          latexmk_use_lualatex: true
          args: -gg -halt-on-error -file-line-error
          pre_compile: |
            tlmgr update --self --all
            tlmgr install \
              luatexja luatexja-fontspec ipaex \
              siunitx booktabs cite bm \
              pgf tikz caption subcaption \
              multirow array float hyperref \
              collection-latexrecommended collection-fontsrecommended collection-langjapanese

      - name: Upload PDF and LOG
        uses: actions/upload-artifact@v4
        with:
          name: driver-tisi2-ieee
          path: |
            papers/2025_driver_tisi2_ieee/main.pdf
            papers/2025_driver_tisi2_ieee/main.log
