name: Build LaTeX PDF (TFP Actuator)

on:
  push:
    paths:
      - 'papers/2025_tfp_actuator_reliability/**'
      - '.github/workflows/latex_tfp_actuator.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with LuaLaTeX
        id: latex
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: papers/2025_tfp_actuator_reliability
          root_file: main.tex
          latexmk_use_lualatex: true

      # 生成物の在処を可視化（デバッグ用）
      - name: Show build outputs
        if: always()
        run: |
          echo "== CWD ==" && pwd
          echo "== tree papers/2025_tfp_actuator_reliability =="
          ls -la papers/2025_tfp_actuator_reliability || true

      - name: Upload PDF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfp_actuator_pdf
          path: papers/2025_tfp_actuator_reliability/main.pdf

      - name: Upload LOG
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfp_actuator_log
          path: papers/2025_tfp_actuator_reliability/main.log
