name: Build LaTeX PDF (TFP Actuator)

on:
  push:
    paths:
      - 'latex-papers/papers/2025_tfp_actuator_reliability/**'
      - '.github/workflows/latex_tfp_actuator.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with LuaLaTeX
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: latex-papers/papers/2025_tfp_actuator_reliability
          root_file: main.tex
          latexmk_use_lualatex: true
          # 必須パッケージをまとめて導入（日本語＋TikZ＋周辺）
          pre_compile: |
            tlmgr update --self
            # 日本語フルセット（HaranoAji含む）
            tlmgr install collection-langjapanese
            # LuaLaTeX周り（latexmkも明示）
            tlmgr install collection-luatex latexmk
            # 図表・ユーティリティ
            tlmgr install pgf xcolor siunitx booktabs hyperref caption subcaption geometry float standalone
            # 念のため（不足時の保険）
            tlmgr install luatexja luatexja-preset

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: tfp_actuator_pdf
          path: latex-papers/papers/2025_tfp_actuator_reliability/main.pdf

      - name: Upload LOG
        uses: actions/upload-artifact@v4
        with:
          name: tfp_actuator_log
          path: latex-papers/papers/2025_tfp_actuator_reliability/main.log
