name: Build LaTeX PDF (Humanoid TCST)

on:
  push:
    paths:
      - 'edusemi/papers/2025_humanoid_tcst/**.tex'
      - 'edusemi/papers/2025_humanoid_tcst/**.bib'
      - '.github/workflows/latex_humanoid_tcst.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: edusemi/papers/2025_humanoid_tcst
          latexmk_use_xelatex: true
          continue_on_error: false

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: humanoid_tcst_pdf
          path: edusemi/papers/2025_humanoid_tcst/main.pdf
