name: Build LPDDR+FeRAM Paper

on:
  push:
    paths:
      - 'papers/2025_lpddr_feram/**'
      - '.github/workflows/latex_lpddr_feram.yml'
  workflow_dispatch:

concurrency:
  group: lpddr-feram-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX (latexmk + pdflatex)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: papers/2025_lpddr_feram
          latexmk_use_pdflatex: true     # ← ここを有効化
          latexmk_use_lualatex: false    # ← LuaLaTeXは無効化
          latexmk_shell_escape: true
          cache: true

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: lpddr-feram-paper
          path: papers/2025_lpddr_feram/main.pdf
          if-no-files-found: error
          retention-days: 14
