name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  workflow_dispatch:
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify target folder exists
        run: |
          test -d papers/2025_fefet_cmos018_reliability || {
            echo "papers/2025_fefet_cmos018_reliability not found"; exit 1; }
          ls -al papers/2025_fefet_cmos018_reliability
          test -f papers/2025_fefet_cmos018_reliability/main.tex

      # latexmk が必要回数の再コンパイルを自動実行（クロスリファレンスの ?? を解消）
      - name: Build LaTeX with latexmk (lualatex)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: papers/2025_fefet_cmos018_reliability
          latexmk_use_lualatex: true
          # -pdf は latexmk に PDF を作らせる（複数回走る）
          args: -pdf -file-line-error -interaction=nonstopmode

      # 失敗時にも中身を確認できるようにログ・中間生成物を全部アップロード
      - name: Upload PDF and logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            papers/2025_fefet_cmos018_reliability/*.pdf
            papers/2025_fefet_cmos018_reliability/*.log
            papers/2025_fefet_cmos018_reliability/*.aux
            papers/2025_fefet_cmos018_reliability/*.fls
            papers/2025_fefet_cmos018_reliability/*.fdb_latexmk
            papers/2025_fefet_cmos018_reliability/*.synctex.gz
          if-no-files-found: warn
