name: latex_cd50_boa_v4

on:
  workflow_dispatch:
  push:
    paths:
      - "latex-papers/papers/2025_cd50_boa/**"
      - "latex-papers/.github/workflows/latex_cd50_boa_v4.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PAPER_DIR: latex-papers/papers/2025_cd50_boa
      ROOT_TEX: main.tex

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-small
            latexmk
            collection-luatex
            collection-langjapanese
            collection-fontsrecommended
            luatexja
            url
            hyperref
            amsmath
            amssymb
            graphics
            xcolor

      - name: Build (latexmk lualatex)
        working-directory: ${{ env.PAPER_DIR }}
        run: |
          latexmk -lualatex -shell-escape -interaction=nonstopmode -file-line-error -synctex=1 -halt-on-error "${{ env.ROOT_TEX }}" \
          || echo "LaTeX build failed, see log"

      - name: Upload PDF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cd50_boa_pdf
          path: ${{ env.PAPER_DIR }}/main.pdf
          if-no-files-found: warn

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cd50_boa_logs
          path: |
            ${{ env.PAPER_DIR }}/main.log
            ${{ env.PAPER_DIR }}/main.fdb_latexmk
            ${{ env.PAPER_DIR }}/main.fls
          if-no-files-found: warn
