name: Build LaTeX PDF (FeFET CMOS018 Reliability) 

on:
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify target files
        id: verify
        shell: bash
        run: |
          set -e
          DIR="papers/2025_fefet_cmos018_reliability"
          echo "HEAD: $(git rev-parse HEAD)"
          echo "== git ls-files in $DIR =="
          git ls-files "$DIR/*" || true
          echo "== ls -al $DIR =="
          ls -al "$DIR" || true
          if [[ -f "$DIR/main.tex" ]]; then
            echo "found_main=true" >> "$GITHUB_OUTPUT"
          else
            echo "found_main=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Build LaTeX (LuaLaTeX)
        if: steps.verify.outputs.found_main == 'true'
        uses: xu-cheng/latex-action@v3
        with:
          root_file: papers/2025_fefet_cmos018_reliability/main.tex
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode

      - name: Fallback log (always)
        if: always()
        shell: bash
        run: |
          DIR="papers/2025_fefet_cmos018_reliability"
          OUT="reliability_run_info.txt"
          {
            echo "==== Reliability build context ===="
            echo "UTC: $(date -u)"
            echo "HEAD: $(git rev-parse HEAD)"
            echo "found_main: ${FOUND:-${{ steps.verify.outputs.found_main }}}"
            echo "--- repo root (top 2 levels) ---"
            find . -maxdepth 2 -type d -printf "%p/\n" | sort
            echo "--- ls -al $DIR ---"
            ls -al "$DIR" || echo "(directory missing)"
          } > "$OUT"
          # もしディレクトリが存在すれば console.log も出す（存在しなくても失敗しない）
          if [[ -d "$DIR" ]]; then
            cp "$OUT" "$DIR/console.log" || true
          fi

      - name: Upload PDF & logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            papers/2025_fefet_cmos018_reliability/main.pdf
            papers/2025_fefet_cmos018_reliability/main.log
            papers/2025_fefet_cmos018_reliability/console.log
            reliability_run_info.txt
          if-no-files-found: warn
