name: Build LaTeX Review (DRAM-FeRAM)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'special/review_dram_feram/**'
      - '.github/workflows/latex_review.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: special/review_dram_feram
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up TeX Live
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: small
          packages: >-
            latexmk
            latex-bin
            collection-latexrecommended
            collection-fontsrecommended
            bibtex
            lmodern
            siunitx
            booktabs
            ieeeconf

      - name: Build PDF
        run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: review_dram_feram_pdf
          path: special/review_dram_feram/main.pdf
