name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify target files
        id: verify
        run: |
          DIR="papers/2025_fefet_cmos018_reliability"
          echo "HEAD: $(git rev-parse HEAD)"
          echo "== ls -al $DIR =="
          ls -al "$DIR" || true
          test -f "$DIR/main.tex" && echo "found_main=true" >> $GITHUB_OUTPUT || echo "found_main=false" >> $GITHUB_OUTPUT

      - name: Build LaTeX (LuaLaTeX)
        if: steps.verify.outputs.found_main == 'true'
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex                      # ファイル名のみ
          working_directory: papers/2025_fefet_cmos018_reliability
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode

      - name: Tail main.log on failure
        if: failure()
        run: |
          tail -n 200 papers/2025_fefet_cmos018_reliability/main.log || true

      - name: Fallback context log (always)
        if: always()
        run: |
          DIR="papers/2025_fefet_cmos018_reliability"
          {
            echo "==== Reliability build context ===="
            echo "UTC: $(date -u)"
            echo "HEAD: $(git rev-parse HEAD)"
            echo "found_main: ${{ steps.verify.outputs.found_main }}"
            echo "--- repo root (top 2 levels) ---"
            find . -maxdepth 2 -type d -printf "%p/\n" | sort
            echo "--- ls -al $DIR ---"
            ls -al "$DIR" || echo "(directory missing)"
          } > reliability_run_info.txt
          if [ -d "$DIR" ]; then
            cp reliability_run_info.txt "$DIR/console.log" || true
          fi

      - name: Upload PDF & logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            papers/2025_fefet_cmos018_reliability/main.pdf
            papers/2025_fefet_cmos018_reliability/main.log
            papers/2025_fefet_cmos018_reliability/console.log
            reliability_run_info.txt
          if-no-files-found: warn
