name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ある / ない を確認（失敗しても続行）
      - name: Debug file tree
        run: |
          echo "PWD=$(pwd)" || true
          ls -la || true
          ls -la papers || true
          ls -la papers/2025_fefet_cmos018_reliability || true

      - name: Build LaTeX (lualatex)
        uses: xu-cheng/latex-action@v2
        with:
          # ← working_directory は使わず、root_file にフルパスを指定
          root_file: papers/2025_fefet_cmos018_reliability/main.tex
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode

      - name: Upload PDF and Log
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            papers/2025_fefet_cmos018_reliability/main.pdf
            papers/2025_fefet_cmos018_reliability/main.log
