name: latex_dram_vsram_history
on:
  push:
    paths:
      - "papers/2025_dram_vsram_history/**"
      - ".github/workflows/latex_dram_vsram_history.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: papers/2025_dram_vsram_history
          latexmk_use_xelatex: true
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: dram_vsram_history_pdf
          path: papers/2025_dram_vsram_history/*.pdf
