name: Build LaTeX (fefet_cmos018)

on:
  push:
    paths:
      - "papers/2025_fefet_cmos018/**"          # ここに refs.bib も含まれる
      - ".github/workflows/latex_fefet_cmos018.yml"
  workflow_dispatch:

jobs:
  build-fefet:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live + Pandoc (XeLaTeX & CJK)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            latexmk \
            texlive-xetex texlive-latex-base texlive-latex-recommended texlive-latex-extra \
            texlive-fonts-recommended texlive-fonts-extra \
            texlive-pictures texlive-science texlive-bibtex-extra \
            texlive-publishers texlive-lang-cjk ghostscript \
            fonts-noto-cjk fonts-noto-cjk-extra

      - name: Clean old build
        working-directory: papers/2025_fefet_cmos018
        run: |
          rm -f *.aux *.bbl *.blg *.fdb_latexmk *.fls *.out *.toc *.lof *.lot *.log *.pdf || true
          rm -rf build || true
          mkdir -p build

      - name: Convert Markdown to TeX (sections -> build)
        working-directory: papers/2025_fefet_cmos018
        run: |
          for f in sections/*.md; do
            fname=$(basename "$f" .md)
            echo "Converting $f -> build/$fname.tex"
            pandoc "$f" -o "build/$fname.tex" -t latex --wrap=none
          done
          ls -la build

      - name: Build PDF with XeLaTeX (3-pass + BibTeX)
        working-directory: papers/2025_fefet_cmos018
        env:
          LANG: C.UTF-8
        run: |
          set -e
          # 1st LaTeX で .aux を作成
          xelatex -file-line-error -interaction=nonstopmode main.tex || true

          # BibTeX 実行（.aux が無い/refs.bib が無い場合は明示的に失敗）
          if [ ! -f main.aux ]; then
            echo "::error::main.aux が生成されていません（LaTeX 1st pass 失敗）"; exit 1
          fi
          if ! grep -q "\citation" main.aux; then
            echo "No citations found in main.aux -> それでも BibTeX を実行します"
          fi
          bibtex main || true

          # 追加の安全チェック：refs.bib を開けなかったら落とす
          if grep -q "I couldn't open database file" main.blg; then
            echo "::error::BibTeX が refs.bib を開けませんでした"; exit 1
          fi

          # 2nd/3rd pass
          xelatex -file-line-error -interaction=nonstopmode main.tex || true
          xelatex -file-line-error -interaction=nonstopmode main.tex || true

          echo "==== tail main.log (last 200 lines) ===="
          tail -n 200 main.log || true

          # 参照未解決を検出して落とす
          if grep -q "Undefined citations" main.log || grep -q "LaTeX Warning: Reference .* undefined" main.log ; then
            echo "::error::Undefined citations or references remain."
            exit 1
          fi

          # PDF が無ければ失敗
          if [ ! -f main.pdf ]; then
            echo "::error::PDF was not generated."
            exit 1
          fi

      - name: Upload PDF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018-pdf
          path: papers/2025_fefet_cmos018/main.pdf
          retention-days: 7

      - name: Upload LaTeX logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018-logs
          path: |
            papers/2025_fefet_cmos018/*.log
            papers/2025_fefet_cmos018/*.blg
            papers/2025_fefet_cmos018/*.bbl
            papers/2025_fefet_cmos018/*.aux
            papers/2025_fefet_cmos018/*.fls
            papers/2025_fefet_cmos018/*.fdb_latexmk
          retention-days: 7
