name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ここで main.tex が本当に取れているか強制チェック（無ければ即失敗）
      - name: Verify target folder & files
        run: |
          set -euo pipefail
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          ls -al
          ls -al papers || true
          ls -al papers/2025_fefet_cmos018_reliability || true

          # Git に追跡されているかも確認（0行なら未コミット/別ブランチ）
          echo "== git ls-files check =="
          git ls-files papers/2025_fefet_cmos018_reliability/main.tex || true

          echo "== fatal check =="
          test -d papers/2025_fefet_cmos018_reliability || { echo "ERROR: target dir missing"; exit 1; }
          test -f papers/2025_fefet_cmos018_reliability/main.tex || { echo "ERROR: main.tex missing"; exit 1; }

      # working_directory ではなく root_file にフルパスを与え、cwdの曖昧さを排除
      - name: Build LaTeX (lualatex)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: papers/2025_fefet_cmos018_reliability/main.tex
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode

      # 失敗時でも何かしらログを残す（フォルダが無くても mkdir してから書く）
      - name: Fallback console log (always)
        if: always()
        run: |
          set -e
          d=papers/2025_fefet_cmos018_reliability
          mkdir -p "$d"
          if [ ! -f "$d/main.log" ]; then
            echo "==== No main.log found. Capturing some context ====" > "$d/console.log"
            echo "date: $(date)" >> "$d/console.log"
            echo "ls -al $d :" >> "$d/console.log"
            ls -al "$d" >> "$d/console.log" 2>&1 || true
            echo "git rev-parse HEAD:" >> "$d/console.log"
            git rev-parse HEAD >> "$d/console.log" 2>&1 || true
          fi

      - name: Upload PDF and logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            papers/2025_fefet_cmos018_reliability/main.pdf
            papers/2025_fefet_cmos018_reliability/main.log
            papers/2025_fefet_cmos018_reliability/console.log
          if-no-files-found: warn
          retention-days: 14
