name: Build LaTeX PDF (BioInkjet KNN)

on:
  push:
    branches: [ "main", "develop", "**" ]   # ← どのブランチでも基本発火
    paths:
      - "papers/2025_bioinkjet_knn/**"      # ← 当該ディレクトリに変更がある時
      - ".github/workflows/latex_bioinkjet_knn.yml"  # ← ワークフロー更新でも発火
  pull_request:
    branches: [ "**" ]
    paths:
      - "papers/2025_bioinkjet_knn/**"
      - ".github/workflows/latex_bioinkjet_knn.yml"
  workflow_dispatch: {}                      # ← 手動実行OK

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: papers/2025_bioinkjet_knn

    steps:
      - uses: actions/checkout@v4

      # （任意）TeX Live キャッシュで高速化
      - name: Cache TeX Live
        uses: actions/cache@v4
        with:
          path: ~/.texlive
          key: texlive-${{ runner.os }}-2025

      - name: Compile LaTeX
        id: latex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: papers/2025_bioinkjet_knn
          # XeLaTeX を使う場合は以下を有効化
          # latexmk_use_xelatex: true
          # shell-escape が必要なら有効化
          # latexmk_shell_escape: true
          # 追加パッケージが必要なら（例）
          # extra_system_packages: "ghostscript poppler-utils"

      # PDF を保存（失敗しても必ず実行）
      - name: Upload PDF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bioinkjet_knn-pdf
          path: papers/2025_bioinkjet_knn/main.pdf
          retention-days: 14

      # ログ類を保存（失敗時のデバッグ用）
      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bioinkjet_knn-logs
          path: |
            papers/2025_bioinkjet_knn/*.log
            papers/2025_bioinkjet_knn/*.aux
            papers/2025_bioinkjet_knn/*.fls
            papers/2025_bioinkjet_knn/*.fdb_latexmk
            papers/2025_bioinkjet_knn/*.out
            papers/2025_bioinkjet_knn/*.toc
          retention-days: 14
