# .github/workflows/latex_fefet_cmos018_reliability.yml
name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ここがポイント：論文フォルダを working_directory に指定
      - name: Build (lualatex)
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: papers/2025_fefet_cmos018_reliability
          root_file: main.tex
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode -synctex=1

      - name: Debug list (optional)
        if: always()
        run: |
          ls -al
          ls -al papers/2025_fefet_cmos018_reliability || true

      - name: Upload PDF and log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            papers/2025_fefet_cmos018_reliability/main.pdf
            papers/2025_fefet_cmos018_reliability/main.log
          if-no-files-found: warn
