name: Build AITL Space Paper

on:
  push:
    paths:
      - 'papers/2025_aitl_space/**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: papers/2025_aitl_space/main.tex
          latexmk_use_lualatex: true
          extra_system_packages: "ghostscript"

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: aitl_space_pdf
          path: papers/2025_aitl_space/main.pdf

      - name: Upload LaTeX log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aitl_space_log
          path: papers/2025_aitl_space/main.log
