\documentclass[journal]{IEEEtran}
\usepackage{amsmath,amssymb}
\usepackage{graphicx}
\usepackage{cite}

\begin{document}

\title{Cross-Node Humanoid Robot Control: FSM, PID, State-Space and LLM Integration}
\author{Shinichi Samizo,~\IEEEmembership{Member,~IEEE}, et al.}

\maketitle

\input{abstract}
\begin{IEEEkeywords}
Humanoid Robot, FSM, PID, State-Space Control, LLM, Cross-Node Design, Energy Harvesting
\end{IEEEkeywords}

\input{intro}
\input{related}
\input{system}
\input{results}
\input{discussion}
\input{conclusion}

\bibliographystyle{IEEEtran}
\bibliography{refs}

\end{document}
