name: latex_cd50_boa_v4

on:
  workflow_dispatch:
  push:
    paths:
      - "latex-papers/papers/2025_cd50_boa/**"
      - ".github/workflows/latex_cd50_boa_v4.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PAPER_DIR: latex-papers/papers/2025_cd50_boa
      ROOT_TEX: main.tex

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # パス検証：間違っていたらここで即赤字終了
      - name: Sanity check (paths)
        run: |
          echo "Repo root:" && ls -al
          test -d "${PAPER_DIR}" || (echo "::error ::PAPER_DIR not found: ${PAPER_DIR}" && exit 1)
          test -f "${PAPER_DIR}/${ROOT_TEX}" || (echo "::error ::ROOT_TEX not found: ${PAPER_DIR}/${ROOT_TEX}" && exit 1)
          echo "Found ${PAPER_DIR}/${ROOT_TEX}"

      # texlive-full を使う画像（パッケージ不足を根こそぎ回避）
      - name: Build PDF (LuaLaTeX, texlive-full image)
        id: build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ env.ROOT_TEX }}
          working_directory: ${{ env.PAPER_DIR }}
          compiler: lualatex
          # texlive-full の docker イメージを使用（日本語・フォント・周辺パッケージ一式入り）
          docker_image: ghcr.io/xu-cheng/texlive-full:latest
          args: -interaction=nonstopmode -file-line-error -shell-escape

      # ログ先頭を要約に出す（失敗原因を画面で即把握）
      - name: Dump last 80 lines of main.log
        if: always()
        run: |
          if [ -f "${PAPER_DIR}/main.log" ]; then
            echo '```' >> $GITHUB_STEP_SUMMARY
            tail -n 80 "${PAPER_DIR}/main.log" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "main.log not found in ${PAPER_DIR}" >> $GITHUB_STEP_SUMMARY
          fi

      # 成否にかかわらず PDF とログを回収
      - name: Upload PDF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cd50_boa_pdf
          path: ${{ env.PAPER_DIR }}/main.pdf
          if-no-files-found: warn
          retention-days: 14

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cd50_boa_logs
          path: |
            ${{ env.PAPER_DIR }}/main.log
            ${{ env.PAPER_DIR }}/main.fdb_latexmk
            ${{ env.PAPER_DIR }}/main.fls
          if-no-files-found: warn
          retention-days: 14
