name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 必ず実行して、runner 上のファイルを確認
      - name: Debug file tree
        run: |
          echo "PWD=$(pwd)"
          ls -al
          ls -al papers || true
          ls -al papers/2025_fefet_cmos018_reliability || true
          echo "find results:"
          find papers -maxdepth 3 -type f -iname "main*.tex" -print

      - name: Build LaTeX (lualatex)
        uses: xu-cheng/latex-action@v2
        with:
          # ここは「ファイル名のみ」。パスは working_directory で指定
          root_file: main.tex
          working_directory: papers/2025_fefet_cmos018_reliability
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode

      - name: Upload PDF and log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            papers/2025_fefet_cmos018_reliability/main.pdf
            papers/2025_fefet_cmos018_reliability/main.log
          if-no-files-found: warn
