name: Build LaTeX (0.18um 1f-noise paper)

on:
  push:
    paths:
      - "papers/2025_cmos018_noise/**"
      - ".github/workflows/latex_cmos018_noise.yml"
  pull_request:
    paths:
      - "papers/2025_cmos018_noise/**"
      - ".github/workflows/latex_cmos018_noise.yml"
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repo tree (debug)
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          echo "---- target dir ----"
          ls -la papers/2025_cmos018_noise || true

      - name: Compile LaTeX (latexmk → PDF)
        continue-on-error: true   # ← ビルド失敗でも後続を継続
        uses: xu-cheng/latex-action@v3
        with:
          root_file: papers/2025_cmos018_noise/main.tex
          args: -pdf -interaction=nonstopmode -file-line-error

      - name: Verify generated files
        if: always()
        run: |
          echo "---- file list ----"
          find papers/2025_cmos018_noise -maxdepth 1 -type f -printf "%p\t(%s bytes)\n" | sort
          echo "---- check main.tex ----"
          if [ -f papers/2025_cmos018_noise/main.tex ]; then
            wc -c papers/2025_cmos018_noise/main.tex
          else
            echo "main.tex NOT FOUND"
          fi

      # ▼ main.tex を単体でアップロード（必ず入る）
      - name: Upload source main.tex
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cmos018_noise_source_maintex
          path: papers/2025_cmos018_noise/main.tex
          if-no-files-found: warn
          retention-days: 30

      # PDF（存在すれば）
      - name: Upload PDF
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cmos018_noise_pdf
          path: papers/2025_cmos018_noise/main.pdf
          if-no-files-found: warn
          retention-days: 14

      # LOG 類
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cmos018_noise_logs
          path: |
            papers/2025_cmos018_noise/*.log
            papers/2025_cmos018_noise/*.aux
            papers/2025_cmos018_noise/*.bbl
            papers/2025_cmos018_noise/*.blg
            papers/2025_cmos018_noise/*.fls
            papers/2025_cmos018_noise/*.fdb_latexmk
            papers/2025_cmos018_noise/*.out
            papers/2025_cmos018_noise/*.toc
          if-no-files-found: warn
          retention-days: 14

      # ディレクトリ全体のスナップショット
      - name: Upload workdir snapshot
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cmos018_noise_all
          path: papers/2025_cmos018_noise/**
          if-no-files-found: warn
          retention-days: 7
