name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 念のため存在確認（ログに出す）
      - name: Verify files
        run: |
          ls -al papers/2025_fefet_cmos018_reliability
          test -f papers/2025_fefet_cmos018_reliability/main.tex

      - name: Build LaTeX (lualatex)
        uses: xu-cheng/latex-action@v3
        with:
          # ここを“ディレクトリ”ではなく“TeXファイルのパス”にする
          root_file: papers/2025_fefet_cmos018_reliability/main.tex
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode

      - name: Upload PDF and log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            papers/2025_fefet_cmos018_reliability/main.pdf
            papers/2025_fefet_cmos018_reliability/main.log
          if-no-files-found: warn
