name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug file tree
        run: |
          echo "PWD=$(pwd)"
          ls -R papers/2025_fefet_cmos018_reliability

      - name: Build LaTeX (lualatex)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: papers/2025_fefet_cmos018_reliability/main.tex
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode

      - name: Upload PDF and log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            papers/2025_fefet_cmos018_reliability/main.pdf
            papers/2025_fefet_cmos018_reliability/main.log
          if-no-files-found: warn
