name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # デバッグ：リポジトリのファイルツリー確認
      - name: Debug file tree
        run: |
          pwd
          ls -la
          ls -la papers
          ls -la papers/2025_fefet_cmos018_reliability

      - name: Build LaTeX (lualatex)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: ./papers/2025_fefet_cmos018_reliability
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode

      - name: Upload PDF and Log
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            papers/2025_fefet_cmos018_reliability/main.pdf
            papers/2025_fefet_cmos018_reliability/main.log
