name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ここで main.tex の存在を強制チェック
      - name: Verify target files
        run: |
          echo "HEAD: $(git rev-parse HEAD)"
          echo "== git ls-files (target dir) =="
          git ls-files 'papers/2025_fefet_cmos018_reliability/*' || true
          echo "== list target dir =="
          ls -al papers/2025_fefet_cmos018_reliability || true
          test -f papers/2025_fefet_cmos018_reliability/main.tex || \
            (echo "::error::main.tex not found in papers/2025_fefet_cmos018_reliability"; exit 1)

      - name: Build LaTeX (LuaLaTeX)
        uses: xu-cheng/latex-action@v3
        with:
          # パスをフルで渡す（working_directory を使わない）
          root_file: papers/2025_fefet_cmos018_reliability/main.tex
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode

      # もし main.log が出来ていなければ、状況を console.log に落とす
      - name: Fallback log (if missing)
        if: always()
        run: |
          d=papers/2025_fefet_cmos018_reliability
          if [ ! -f "$d/main.log" ]; then
            {
              echo "==== No main.log found. Capturing some context ===="
              echo "date: $(date -u)"
              echo "HEAD: $(git rev-parse HEAD)"
              echo "== ls -al $d =="
              ls -al "$d" || true
            } > "$d/console.log"
          fi

      - name: Upload PDF & logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts
          path: |
            papers/2025_fefet_cmos018_reliability/main.pdf
            papers/2025_fefet_cmos018_reliability/main.log
            papers/2025_fefet_cmos018_reliability/console.log
          if-no-files-found: warn
