name: Build LPDDR+FeRAM Paper

on:
  push:
    paths:
      - 'papers/2025_lpddr_feram/**'
      - '.github/workflows/latex_lpddr_feram.yml'
  workflow_dispatch:

concurrency:
  group: lpddr-feram-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: papers/2025_lpddr_feram
          compiler: pdflatex          # ← これだけで十分
          latexmk_shell_escape: true

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: lpddr-feram-paper
          path: papers/2025_lpddr_feram/main.pdf
          if-no-files-found: error
          retention-days: 14

      # 任意：失敗時に LaTeX のログを回収
      - name: Upload LaTeX logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: latex-logs
          path: papers/2025_lpddr_feram/*.log
