name: Build LaTeX PDF (FeFET CMOS018 Reliability)

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'papers/2025_fefet_cmos018_reliability/**'
      - '.github/workflows/latex_fefet_cmos018_reliability.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Verify sources
        run: |
          ls -al papers/2025_fefet_cmos018_reliability || true
          test -f papers/2025_fefet_cmos018_reliability/main.tex

      - name: Build LaTeX (LuaLaTeX)
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: papers/2025_fefet_cmos018_reliability
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
          args: -file-line-error -interaction=nonstopmode

      - name: Upload PDF and log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fefet_cmos018_reliability_artifacts   # ← Reliability専用名
          path: |
            papers/2025_fefet_cmos018_reliability/main.pdf
            papers/2025_fefet_cmos018_reliability/main.log
          if-no-files-found: warn
