name: Build LaTeX PDF (Humanoid TCST)

on:
  push:
    paths:
      - 'papers/2025_humanoid_tcst/**'     # ← ここをリポジトリ相対に
      - '.github/workflows/latex_humanoid_tcst.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: papers/2025_humanoid_tcst   # ← edusemi/ を外す
          root_file: main.tex
          latexmk_use_xelatex: true
          continue_on_error: false

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: humanoid_tcst_pdf
          path: papers/2025_humanoid_tcst/main.pdf       # ← ここも同様
